resources:
- name: cf-smoke-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-smoke-tests.git
    branch: master
- name: pipeline
  type: git
  source:
    uri: https://github.com/jacek-rzrz/cf-smoke-tests-concourse.git
    branch: master
- name: cf-config
  type: s3
  source:
    bucket: cf-smoke-tests-concourse
    region_name: eu-west-1
    regexp: integration_config-(.*).json
    access_key_id: {{access_key_id}}
    secret_access_key: {{secret_access_key}}
- name: every-10-minutes
  type: time
  source: {interval: 10m}
jobs:
- name: run-smoke-tests
  plan:
  - get: cf-smoke-tests
  - get: pipeline
  - get: cf-config
  - get: every-10-minutes
    trigger: true
  - task: run-smoke-tests
    file: pipeline/tasks/run-smoke-tests.yml
